-- ReduxCoreX Supabase setup
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text not null,
  avatar_url text,
  created_at timestamptz not null default now()
);

alter table public.profiles add column if not exists display_name text;
update public.profiles set display_name=coalesce(display_name, username) where display_name is null;
create unique index if not exists profiles_username_lower_unique on public.profiles (lower(username));

-- username is the login name; display_name is the visible name.
create or replace function public.get_email_by_username(login_username text)
returns text
language sql
security definer
set search_path = public
as $$
  select u.email
  from public.profiles p
  join auth.users u on u.id=p.id
  where lower(p.username)=lower(trim(login_username))
  limit 1;
$$;
revoke all on function public.get_email_by_username(text) from public;
grant execute on function public.get_email_by_username(text) to anon, authenticated;

create table if not exists public.download_history (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  item_name text not null,
  category text not null,
  downloaded_at timestamptz not null default now()
);

alter table public.profiles enable row level security;
alter table public.download_history enable row level security;

drop policy if exists "profiles_select_own" on public.profiles;
create policy "profiles_select_own" on public.profiles for select using (auth.uid() = id);

drop policy if exists "profiles_insert_own" on public.profiles;
create policy "profiles_insert_own" on public.profiles for insert with check (auth.uid() = id);

drop policy if exists "profiles_update_own" on public.profiles;
create policy "profiles_update_own" on public.profiles for update using (auth.uid() = id) with check (auth.uid() = id);

drop policy if exists "history_select_own" on public.download_history;
create policy "history_select_own" on public.download_history for select using (auth.uid() = user_id);

drop policy if exists "history_insert_own" on public.download_history;
create policy "history_insert_own" on public.download_history for insert with check (auth.uid() = user_id);

insert into storage.buckets (id, name, public)
values ('avatars', 'avatars', true)
on conflict (id) do nothing;

drop policy if exists "avatar_public_read" on storage.objects;
create policy "avatar_public_read" on storage.objects for select using (bucket_id = 'avatars');

drop policy if exists "avatar_upload_own_folder" on storage.objects;
create policy "avatar_upload_own_folder" on storage.objects for insert to authenticated
with check (bucket_id = 'avatars' and (storage.foldername(name))[1] = auth.uid()::text);

drop policy if exists "avatar_update_own_folder" on storage.objects;
create policy "avatar_update_own_folder" on storage.objects for update to authenticated
using (bucket_id = 'avatars' and (storage.foldername(name))[1] = auth.uid()::text)
with check (bucket_id = 'avatars' and (storage.foldername(name))[1] = auth.uid()::text);

drop policy if exists "avatar_delete_own_folder" on storage.objects;
create policy "avatar_delete_own_folder" on storage.objects for delete to authenticated
using (bucket_id = 'avatars' and (storage.foldername(name))[1] = auth.uid()::text);

-- Automatically create an empty profile whenever a new auth user is created.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, username, display_name) values (new.id, coalesce(new.raw_user_meta_data->>'username', split_part(new.email, '@', 1)), coalesce(new.raw_user_meta_data->>'display_name', new.raw_user_meta_data->>'username', split_part(new.email, '@', 1)))
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();


-- Public participant profiles and administrator-controlled support reports.
-- Profiles contain no email column, so exposing these fields does not expose account email.
drop policy if exists "profiles_public_select" on public.profiles;
create policy "profiles_public_select" on public.profiles for select using (true);

create or replace function public.is_current_user_admin()
returns boolean
language sql
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid()
      and lower(trim(username)) = 'administrator'
  );
$$;
revoke all on function public.is_current_user_admin() from public;
grant execute on function public.is_current_user_admin() to authenticated;

create table if not exists public.reports (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  reporter_username text not null,
  message text not null check (char_length(message) between 5 and 2000),
  status text not null default 'open' check (status in ('open','in_progress','closed')),
  admin_id uuid references auth.users(id) on delete set null,
  admin_username text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.reports enable row level security;

drop policy if exists "reports_select_own_or_admin" on public.reports;
create policy "reports_select_own_or_admin" on public.reports
for select using (auth.uid() = user_id or public.is_current_user_admin());

drop policy if exists "reports_insert_own" on public.reports;
create policy "reports_insert_own" on public.reports
for insert with check (auth.uid() = user_id);

drop policy if exists "reports_update_admin" on public.reports;
create policy "reports_update_admin" on public.reports
for update using (public.is_current_user_admin()) with check (public.is_current_user_admin());

create or replace function public.set_reports_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists reports_updated_at on public.reports;
create trigger reports_updated_at
before update on public.reports
for each row execute procedure public.set_reports_updated_at();


create or replace function public.set_reporter_username()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  select p.username into new.reporter_username
  from public.profiles p
  where p.id = new.user_id;
  return new;
end;
$$;

drop trigger if exists reports_set_reporter_username on public.reports;
create trigger reports_set_reporter_username
before insert on public.reports
for each row execute procedure public.set_reporter_username();

-- API permissions required for the website.
grant select on public.profiles to anon, authenticated;
grant select, insert, update on public.reports to authenticated;
grant usage, select on sequence public.reports_id_seq to authenticated;
grant execute on function public.is_current_user_admin() to authenticated;


-- =========================================
-- REPORT CHAT
-- =========================================

create table if not exists public.report_chat_messages (
  id bigint generated by default as identity primary key,
  report_id bigint not null references public.reports(id) on delete cascade,
  sender_id uuid not null references auth.users(id) on delete cascade,
  sender_username text,
  message text not null check (char_length(message) between 1 and 2000),
  created_at timestamptz not null default now()
);

alter table public.report_chat_messages enable row level security;

create or replace function public.set_chat_sender_username()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  select p.username
  into new.sender_username
  from public.profiles p
  where p.id = new.sender_id;
  return new;
end;
$$;

drop trigger if exists report_chat_set_sender_username
on public.report_chat_messages;

create trigger report_chat_set_sender_username
before insert on public.report_chat_messages
for each row
execute procedure public.set_chat_sender_username();

drop policy if exists "chat_select_participants"
on public.report_chat_messages;

create policy "chat_select_participants"
on public.report_chat_messages
for select
using (
  exists (
    select 1
    from public.reports r
    where r.id = report_chat_messages.report_id
      and r.status = 'in_progress'
      and (r.user_id = auth.uid() or r.admin_id = auth.uid())
  )
);

drop policy if exists "chat_insert_participants"
on public.report_chat_messages;

create policy "chat_insert_participants"
on public.report_chat_messages
for insert
with check (
  sender_id = auth.uid()
  and exists (
    select 1
    from public.reports r
    where r.id = report_chat_messages.report_id
      and r.status = 'in_progress'
      and (r.user_id = auth.uid() or r.admin_id = auth.uid())
  )
);

grant select, insert
on public.report_chat_messages
to authenticated;

grant usage, select
on sequence public.report_chat_messages_id_seq
to authenticated;

grant execute
on function public.set_chat_sender_username()
to authenticated;

notify pgrst, 'reload schema';
